### ISSUE TITLE
Issue with babel runtime regenerator

### ISSUE THREAD

**Issue by kainoa21** [fitzgen/wu.js#28]
> var wu = require('./dist/wu.js');
TypeError: Cannot read property 'regeneratorRuntime' of undefined
    at wu.js/dist/wu.js:3427:24
    at Object.<anonymous> (wu.js/dist/wu.js:4020:4)
    at Object.module.exports (wu.js/dist/wu.js:4025:31)
    at __webpack_require__ (wu.js/dist/wu.js:30:30)
    at Object.<anonymous> (wu.js/dist/wu.js:3377:19)
    at Object.<anonymous> (wu.js/dist/wu.js:3393:31)
    at __webpack_require__ (wu.js/dist/wu.js:30:30)
    at Object.<anonymous> (wu.js/dist/wu.js:67:28)
    at __webpack_require__ (wu.js/dist/wu.js:30:30)
    at wu.js/dist/wu.js:50:18

**Comment by kainoa21** [comment]
Apologies, this only happens when running node in harmony mode.
